# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: 
  # Archives: /archives/
  Tech: https://alg.xiang578.com
  Tags: /tags
  Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

pjax: true

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode: /img/wechat.jpg
  alipay: /img/alipay.jpg

# ===========================================
# Social links Settings
# ===========================================
social:
  email: i@xiang578.com
  stack-overflow:
  twitter: https://twitter.com/xiang578
  facebook: https://www.facebook.com/profile.php?id=100009528134157
  linkedin: https://www.linkedin.com/in/%E9%97%B0%E5%86%B6-%E9%A1%B9-a2b708134/
  google:
  github: https://github.com/xiang578
  weibo: https://weibo.com/u/1630193304
  zhihu: https://www.zhihu.com/people/xiang578/activities
  douban: https://www.douban.com/people/xiang578/
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: rrSjo9LK0keh9l15bYOQScDF-gzGzoHsz
  app_key: SHpy5xi5vjhNA7cz7THf03vk

# Baidu Analytics
baidu_analytics: d0cbaae42702a7213f06cb394a34a120
# Baidu Verification
baidu_verification: xf6fMthFjE

# Google Analytics
google_analytics: 
# Google Verification
google_verification: TWXGagJ1F37oqHnV7_lLU_ZDeJ1zzwseILCwLz9Dii8

# Disqus
disqus_shortname: xiang578

#Changyan
changyan:
  appid:
  appkey:

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: true

#LiveRe
livere_datauid:

# ===========================================
# Version
# ===========================================
version: 2.11.0
